version: "3.9"

services:
  app-service:
    image: ghcr.io/doda2025-team4/app:latest
    container_name: app-service     
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MODEL_HOST: "http://model-service:${MODEL_SERVICE_PORT}"
    depends_on:
      - model-service
    ports:
      - "${HOST_APP_PORT}:${SERVER_PORT}"
    restart: unless-stopped

  model-service:
    image: ghcr.io/doda2025-team4/model-service:latest
    container_name: model-service
    environment:
      MODEL_SERVICE_PORT: ${MODEL_SERVICE_PORT}
      MODEL_DIR: ${MODEL_DIR}
      MODEL_FILE: ${MODEL_FILE}
      PREPROCESSOR_FILE: ${PREPROCESSOR_FILE}
      MODEL_URL: ${MODEL_URL}
      PREPROCESSOR_URL: ${PREPROCESSOR_URL}
    volumes:
      - ./model-storage:/models:Z
    restart: unless-stopped
