version: "3.9"

services:
  app-service:
    image: ghcr.io/doda2025-team4/app:latest
    container_name: app-service     
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MODEL_HOST: ${MODEL_HOST}
    depends_on:
      - model-service
    ports:
      - "${HOST_APP_PORT}:${SERVER_PORT}"
    restart: unless-stopped

  model-service:
    image: ghcr.io/doda2025-team4/model-service:latest
    container_name: model-service
    environment:
      MODEL_SERVICE_PORT: ${MODEL_SERVICE_PORT}
      MODEL_DIR: /models
      MODEL_FILE: model.joblib
      MODEL_URL: https://github.com/doda2025-team4/model-service/releases/download/model-20251121-132231/model.joblib
    volumes:
      - ./model-storage:/models:z
    restart: unless-stopped
