version: "3.9"

services:
  app-service:
    image: ghcr.io/doda2025-team4/app:latest
    container_name: app-service     
    environment:
      MODEL_URL: "http://model-service:8081" 
    depends_on:
      - model-service
    ports:
      - "8080:8080"
    restart: unless-stopped

  model-service:
    image: ghcr.io/doda2025-team4/model-service:latest
    container_name: model-service
    #volumes: Needed for F10
    #  - ./model:/app/model   
    restart: unless-stopped
