version: "3.9"

services:
  app-service:
    image: ghcr.io/doda2025-team4/app:latest
    container_name: app-service     
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MODEL_HOST: "http://model-service:${MODEL_SERVICE_PORT}"
    depends_on:
      - model-service
    ports:
      - "${HOST_APP_PORT}:${SERVER_PORT}"
    restart: unless-stopped

  model-service:
    image: test_model #ghcr.io/doda2025-team4/model-service:latest
    container_name: model-service
    environment:
      MODEL_SERVICE_PORT: ${MODEL_SERVICE_PORT}
      MODEL_DIR: /models
      MODEL_FILE: model.joblib
      PREPROCESSOR_FILE: preprocessor.joblib
      MODEL_URL: https://github.com/doda2025-team4/model-service/releases/download/model-20251205-113245/model.joblib
      PREPROCESSOR_URL: https://github.com/doda2025-team4/model-service/releases/download/model-20251205-113245/preprocessor.joblib
    volumes:
      - ./model-storage:/models:Z
    restart: unless-stopped
