apiVersion: v1
kind: ConfigMap
metadata:
  name: doda-alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_from: "{{ .Values.alerting.smtp.from }}"
      smtp_smarthost: "{{ .Values.alerting.smtp.host }}"
      smtp_auth_username: "{{ .Values.alerting.smtp.username }}"
      smtp_auth_password: "{{ .Values.alerting.smtp.password }}"
    route:
      receiver: "email-alert"
    receivers:
      - name: "email-alert"
        email_configs:
          - to: "{{ .Values.alerting.smtp.to }}"
            send_resolved: true
