{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | quote }}
      http:
        paths:
          - path: {{ (index .Values.ingress.hosts 0).path | quote }}
            pathType: Prefix
            backend:
              service:
                name: app-service-stable
                port:
                  number: {{ .Values.app.service.port }}
{{- end }}
