apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: {{ .Values.model.replicaCount }}
  selector:
    matchLabels:
      app: model-service
      version: stable
  template:
    metadata:
      labels:
        app: model-service
        version: stable
    spec:
      containers:
        - name: model-container
          image: "{{ .Values.model.image.repository }}:{{ .Values.model.image.tag }}"
          imagePullPolicy: {{ .Values.model.image.pullPolicy }}
          env:
            - name: MODEL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: MODEL_SERVICE_PORT
            - name: MODEL_DIR
              valueFrom:
                  configMapKeyRef:
                    name: environment-config
                    key: MODEL_DIR
            - name: MODEL_FILE
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: MODEL_FILE
            - name: PREPROCESSOR_FILE
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: PREPROCESSOR_FILE
            - name: MODEL_URL
              valueFrom:
                  configMapKeyRef:
                    name: environment-config
                    key: MODEL_URL
            - name: PREPROCESSOR_URL
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: PREPROCESSOR_URL
          ports:
            - containerPort: {{ .Values.model.env.port }}
          {{- if .Values.model.storage.enabled }}
          volumeMounts:
            - name: model-storage
              mountPath: {{ .Values.model.env.modelDir }}
          {{- end }}

      {{- if .Values.model.storage.enabled }}
      volumes:
        - name: model-storage
          hostPath:
            path: {{ .Values.model.storage.stableHostPath | quote }}
            type: DirectoryOrCreate
      {{- end }}

