---
- hosts: all
  become: yes
  vars:
    keys: "{{ lookup('fileglob', 'keys/*.pub', wantlist=True) }}"

  tasks:

    # Step 4
    - name: Add team SSH keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ keys }}"

    # Step 5
    - name: Disable swap at runtime
      ansible.builtin.command: swapoff -a

    - name: Remove swap from /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    # Step 6
    - name: Create modules-load config
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load br_netfilter
      community.general.modprobe:
        name: br_netfilter
        state: present

    # Step 7
    - name: Enable net.ipv4.ip_forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Enable bridged IPv4 forwarding
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes

    - name: Enable bridged IPv6 forwarding
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present
        reload: yes
    
    # Step 8
    - name: Generate /etc/hosts dynamically
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    # Step 9
    - name: Add Kubernetes apt key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: "deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"

    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes

    # Step 10
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - containerd=1.7.24-*
          - runc=1.1.12-*
          - kubeadm=1.32.4-*
          - kubelet=1.32.4-*
          - kubectl=1.32.4-*
        state: present

    # Step 11
    - name: Ensure containerd config directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Disable AppArmor in containerd
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)disable_apparmor ='
        line: '    disable_apparmor = true'

    - name: Set sandbox image
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)sandbox_image ='
        line: '    sandbox_image = "registry.k8s.io/pause:3.10"'

    - name: Enable SystemdCgroup
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup ='
        line: '            SystemdCgroup = true'

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted

    # Step 12
    - name: Enable kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: yes

    # Fix ntp alert
    - name: Set ntp
      ansible.builtin.command: timedatectl set-ntp true
    
    - name: Enable ntp
      ansible.builtin.service:
        name: systemd-timesyncd
        state: started
        enabled: yes

