---
- hosts: nodes
  become: yes
  tasks:
    # Step 18
    - name: Check if node is already joined
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Get join command from ctrl
      ansible.builtin.command: |
        kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      when: not kubelet_conf.stat.exists
    
    # Step 19
    - name: Run join command
      ansible.builtin.shell: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists

